### ISSUE TITLE
Default raster size 256 vs 512

### ISSUE THREAD

**Issue by D3M05** [thesocialdev/kartodock#10]
Hey @thesocialdev , I've been playing with vector tiles and noticed that by default in programs like Openlayers they are loaded at 512 for the tile size.  This causes them to render one zoom level higher than the zoom the map is at, so for example zoom 14 of openlayers loads zoom 13 from kartotherian.  If I change to 256, it loads the "correct" zoom level.  Thing is, I prefer the 512 as it saves on the download size and allows me to prerender at zoom 14 and load the data at 15.   The quest is, can I change the raster size to load at 512px by default to match?  I know I can somewhat get away with rendering @2x, but then everything like icons/fonts/etc is blown up in size and would require scaling down everything to fit.  The static /img/ allows different with and height, which is different than scaling.   There doesn't seem to be a way to pass different sizes to the x/y/z url, but that would be an option as well.  Any feedback or insight is greatly appreciated.  Thanks!

**Comment by thesocialdev** [comment]
@d3mon187 sorry for the long wait. It has been hectic. So, you're saying that requesting tile with scale parameter is not working to you somehow, can you elaborate on that? Example: https://maps.wikimedia.org/osm-intl/4/4/10@2x.png

**Comment by D3M05** [comment]
No worries, totally understand.  Crazy times, haha.  I'm getting pretty familiar with a lot of the pieces, so that's good.

So the issue is more of a native resolution vs kind of a higher dpi of the same resolution.  Easy example is https://maps.wikimedia.org/img/osm-intl,13,29.477,-98.635,512x512.png vs https://maps.wikimedia.org/osm-intl/13/1851/3393@2x.png .   Same 512x512px image size, but the img method covers double the area.

I did manage to get this working, although it still needs some more changes.  Seems to me the tiles are coming out a little more blurry, which you can kind of see in the /img/ link too, so probably not a full fix.  Still, it works well enough for now, and I plan on leaning heavily towards the vector side anyway.  The fix as I have it for now is to go into @kartotherian/tilelive-bridge/index.js and @kartotherian/tilelive-vector/index.js and mostly do a text replace of 256 to 512.   You then have to rework the style to match the new level changes and make sure your rendering program (openlayers) is set for 512 tilesize for raster too, but I think the benefits are worth it for me and now my vector and raster match up.

**Comment by thesocialdev** [comment]
I understand your point, although these are 2 different endpoints and conceptually different. You should avoid using the snapshot service a.k.a. /img endpoint as a tile server, for performance reasons.

I guess your change is the right way, maybe this could be passed as a GET parameter.

**Comment by D3M05** [comment]
Yeah, I just used the two endpoints to explain my resolution vs dpi dilemma.

A way to assign it through GET would be perfect.  I don't think a change to 512 would be a bad route as a whole, but I am all for giving people options.

**Comment by wikiocity** [comment]
You can close this one.  Hopefully an easier way will be added in the future, or someone has one, but you can change the render size in the tilelive-vector node_module from 256 to 512.

**Comment by thesocialdev** [comment]
@wikiocity if you feel the need to have this feature in the future, please move it to [phabricator](https://phabricator.wikimedia.org/project/view/1127/) so we can discuss it in a better venue.
